name: Example
on: 
  push:
    branches:
      main

env:
  PROJECT_VERSION: "1.0.0"

jobs:
  simple-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with: 
          java-version: 17
          distribution: correcto
          
      - name: setVersion
        run: echo $PROJECT_VERSION=${{PROJECT_VERSION}}
      - name: newVersion
        run: echo $PROJECT_VERSION
      - name: clean maven
        run: mvn clean package -DskipTests
        env: 
            MAVEN_OPTS: "-DMaven.repo.local=${{github.workspace}}/.m2/repository"

     
      - name: cache
        id: cache-dependancies
        uses: actions/cache@v4.2.2
        with:
          path: "-DMaven.repo.local=${{github.workspace}}/.m2/repository"
          key: ${{runner.os}}-maven-${{ hashFiles('**/pom.xml')}}
          



