name: Example
on: 
  push

env:
  PROJECT_VERSION: "1.0.0"

jobs:
  simple-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: clean maven
        run: mvn clean package -DskipTests
      - name: setVersion
        run: $PROJECT_VERSION=$PROJECT_VERSION+1
      - name: newVersion
        run: echo $PROJECT_VERSION
     
      - name: Second print
        run: echo "bien2"

