name: Example
on: 
  push:
    branches:
      main

env:
  PROJECT_VERSION: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: cache
        id: cache-dependancies
        uses: actions/cache@v4.1.2
        with:
          path: "-DMaven.repo.local=${{github.workspace}}/.m2/repository"
          key: ${{runner.os}}-maven-${{ hashFiles('**/pom.xml')}}
        
      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with: 
          java-version: 17
          distribution: corretto
          
      - name: newVersion
        run: echo $PROJECT_VERSION
      
      - name: clean maven
        env: 
          MAVEN_OPTS: "-DMaven.repo.local=${{github.workspace}}/.m2/repository"
        run: mvn clean package -DskipTests

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: App_to_deploy
          path: ${{github.workspace}}/target/*.jar

      
  test:
    name: test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: cache
        id: cache-dependancies
        uses: actions/cache@v4.1.2
        with:
          path: "-DMaven.repo.local=${{github.workspace}}/.m2/repository"
          key: ${{runner.os}}-maven-${{ hashFiles('**/pom.xml')}}
        
      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with: 
          java-version: 17
          distribution: corretto
      - name: test ma
        run: mvn test
        env: 
          MAVEN_OPTS: "-DMaven.repo.local=${{github.workspace}}/.m2/repository"
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: cache
        id: cache-dependancies
        uses: actions/cache@v4.1.2
        with:
          path: "-DMaven.repo.local=${{github.workspace}}/.m2/repository"
          key: ${{runner.os}}-maven-${{ hashFiles('**/pom.xml')}}
        
      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with: 
          java-version: 17
          distribution: corretto
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: App_to_deploy
      - name: cat jar
        run: cat ${{github.workspace}}/target/*.jar
        
        
        


